owner: mpiot
repo: status-avirontours

sites:
  - name: Aviron Tours
    url: https://avirontours.fr
  - name: Aviron Tours Métropole
    url: https://www.aviron-tours-metropole.com

status-website:
  cname: status.avirontours.fr
  logoUrl: https://raw.githubusercontent.com/mpiot/avirontours/develop/assets/images/logo_colored.svg
  name: Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/mpiot/avirontours
